export const PERMISSION_CATALOG_DESCRIPTIONS: Record<string, string> = {
  "*": "Complete access to all features in the system",
  "read:all": "Can view all data across the application",
  "write:all": "Can create and update data across the application",
  "manage:all": "Full control over all data and settings",
  "read:users": "Browse the user directory and view user profiles",
  "write:users": "Update user profile details and assignments",
  "manage:users": "Create, edit, delete users and manage accounts",
  "read:teams": "View team structure and membership",
  "write:teams": "Update team details and assignments",
  "manage:teams": "Create, edit, and delete teams",
  "read:assigned_teams": "View teams assigned to the current user",
  "write:assigned_teams": "Update teams the user is assigned to",
  "read:projects": "Browse projects and project details",
  "write:projects": "Update project information and settings",
  "manage:projects": "Create, edit, and delete projects",
  "read:assigned_projects": "View projects assigned to the user",
  "write:assigned_projects": "Update assigned project details",
  "read:candidates": "Browse candidates and view candidate profiles",
  "write:candidates": "Update candidate records and details",
  "bulk_create:candidates": "Bulk create candidates from resume upload",
  "manage:candidates": "Full candidate lifecycle management",
  "read:assigned_candidates": "View candidates assigned to the user",
  "write:assigned_candidates": "Update assigned candidate records",
  "nominate:candidates": "Nominate candidates for projects or roles",
  "approve:candidates": "Approve candidate status or workflow steps",
  "reject:candidates": "Reject candidates in workflow steps",
  "shortlist:candidates": "Add candidates to shortlists for projects",
  "transfer:candidates": "Transfer candidates between recruiters or teams",
  "transfer_back:candidates": "Return transferred candidates to the previous owner",
  "read:documents": "View candidate and process documents",
  "write:documents": "Upload and update documents",
  "verify:documents": "Verify submitted documents for compliance",
  "reject:documents": "Reject submitted documents that do not meet requirements",
  "send:verification": "Send candidates for document verification",
  "manage:documents": "Full document management including verification workflows",
  "request:resubmission": "Request candidates to resubmit documents",
  "read:original_document_intake": "View original document intake register and collections",
  "write:original_document_intake": "Create and manage original document intake collections",
  "read:courier_management": "View courier management register and legs",
  "write:courier_management": "Create and manage courier legs",
  "read:processing": "View processing workflow and steps",
  "write:processing": "Update processing steps and records",
  "manage:processing": "Full control over processing workflows",
  "transfer:processing":
    "Mark passed interviews ready for processing, and move candidates into the processing workflow",
  "read:recruiters": "View recruiter profiles and performance data",
  "write:recruiters": "Update recruiter records and assignments",
  "manage:recruiters": "Manage recruiter accounts and assignments",
  "read:cre": "View operations (CRE) workflows and data",
  "write:cre": "Update operations records and follow-ups",
  "manage:cre": "Manage operations team workflows",
  "assign:cre": "Assign operations handlers to candidates",
  "handle:rnr_candidates": "Work right-to-represent (RNR) candidate cases",
  "read:operations_call_history": "View call history for operations follow-ups",
  "read:roles": "View roles and their permission assignments",
  "write:roles": "Update custom role details",
  "manage:roles": "Create, edit, and delete custom roles",
  "read:agents": "View agent profiles and details",
  "write:agents": "Create new agent records",
  "edit:agents": "Update existing agent records",
  "delete:agents": "Remove agent records from the system",
  "read:clients": "View client organizations and contacts",
  "write:clients": "Update client records and relationships",
  "manage:clients": "Create, edit, and delete clients",
  "read:interviews": "View interview schedules and outcomes",
  "write:interviews": "Update interview records",
  "manage:interviews": "Full interview workflow management",
  "schedule:interviews": "Schedule and reschedule interviews",
  "upload:offer_letters":
    "Upload or re-upload signed offer letters for passed interviews",
  "read:screenings": "View screening sessions and coordination data",
  "write:screenings": "Update screening sessions and coordination",
  "manage:screenings": "Manage screening coordination workflows",
  "conduct:screenings": "Run and complete screening sessions",
  "read:interview_templates": "View screening templates",
  "write:interview_templates": "Create and update screening templates",
  "manage:interview_templates": "Full control over screening templates",
  "read:training": "View training sessions and schedules",
  "write:training": "Update training sessions and content",
  "manage:training": "Manage training programs and sessions",
  "assign:training": "Assign training sessions to users or candidates",
  "read:analytics": "View reports and analytics dashboards",
  "write:analytics": "Configure analytics views and exports",
  "manage:analytics": "Full analytics configuration access",
  "read:settings": "View application settings",
  "write:settings": "Update application settings",
  "manage:settings": "Full settings administration",
  "read:admin-dashboard": "Access the administration dashboard",
  "read:country_coverage": "Browse countries and see which users cover them",
  "read:system_config": "Legacy: view all company setup (prefer per-area reads)",
  "manage:system_config": "Legacy: change all company setup (prefer per-area manages)",
  "read:rnr_settings": "View RNR reminder, office hours, and CRE assignment settings",
  "manage:rnr_settings": "Update RNR reminder, office hours, and CRE assignment settings",
  "read:hrd_settings": "View HRD reminder settings",
  "manage:hrd_settings": "Update HRD reminder settings",
  "read:leadgen_channels": "View WhatsApp, Instagram, Messenger, and Lead Ads channel flags",
  "manage:leadgen_channels": "Enable or disable WhatsApp, Instagram, Messenger, and Lead Ads channels",
  "read:office_addresses": "View office address presets for courier and documents",
  "manage:office_addresses": "Manage office address presets for courier and documents",
  "read:master_catalog": "View professions, departments, and role catalog entries",
  "manage:master_catalog": "Create, update, and deactivate professions, departments, and roles",
  "read:qualifications": "View the educational qualification catalog including inactive entries",
  "manage:qualifications": "Create, update, and deactivate qualifications and aliases",
  "read:audit": "View system audit and activity logs",
  "write:audit": "Create audit log entries",
  "manage:audit": "Manage audit log configuration and retention"
};
