-- No-op: unique index on lockerFileNumber was already added in
-- 20260615120000_add_unique_locker_file_number. This migration was
-- generated by mistake and would fail with "relation already exists".
SELECT 1;
